name: aws_common
description: Common types and utilities used across AWS and Amplify packages.
version: 0.1.0
homepage: https://github.com/aws-amplify/amplify-flutter/packages/aws_common
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: ^2.8.0
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  http: ^0.13.0
  json_annotation: ^4.4.0
  logging: ^1.0.0
  meta: ^1.7.0
  os_detect: ^2.0.0
  path: ^1.8.0
  stream_transform: ^2.0.0
  uuid: 3.0.6

dev_dependencies:
  amplify_lints:
    path: ../amplify_lints
  build_runner: ^2.0.0
  built_value_generator: 8.3.3
  json_serializable: ^6.2.0
  test: ^1.16.0
